In [229]:
import numpy as np

In [230]:
def SOR(A,b,x0, omega, itmax=1000,tolerancia=1e-14):
    x = x0.copy()
    u = x.copy()
    sumk = x.copy()
    residuo = np.linalg.norm( np.dot(A,x) - b)
    it = 0
    while residuo >= tolerancia and it < itmax:
        u[:] = 0
        sumk[:] = 0.
        for i in range(A.shape[0]):
            for j in range(A.shape[1]):
                if i != j:
                    sumk[i] += A[i,j]*x[j]
            u[i] = (1 - omega) * x[i] + (omega / A[i, i]) * (b[i] - sumk[i] - sumk[i-1])
        x = u.copy()
        residuo = np.max(np.abs(np.dot(A,x) - b))
        it += 1
        if residuo > 1000:
            print('No calculable con SOR')
            x[:] = 0.
            break
        
    return x,it

In [231]:
A = np.array([[3, -1, -1], [-1, 3, 1], [2, 1, 4]])
b = np.array([1, 3, 7])
x0 = np.array([0, 0, 0])
Z, iteraciones = SOR(A, b, x0, 1.1)
Z, iteraciones

(array([1, 1, 1]), 2)

In [232]:
it = 1000
x = x0
for i in range(11, 20):
    omega = i/10
    S, ite = SOR(A, b, x0, omega)
    if ite < it:
        it = ite
        x = S
        O = omega
x, it, O

No calculable con SOR


(array([1, 1, 1]), 2, 1.1)

In [233]:
np.linalg.solve(A, b)

array([1., 1., 1.])