In [45]:
import numpy as np
import matplotlib.pyplot as plt

In [46]:
b = np.array([-3, -3, 8, 9])
A = np.array([[3, 1, -1], [1, 2, 0], [0, 1, 2], [1, 1, -1]])

In [47]:
print(A)

[[ 3  1 -1]
 [ 1  2  0]
 [ 0  1  2]
 [ 1  1 -1]]


In [48]:
At = A.T
print(At)

[[ 3  1  0  1]
 [ 1  2  1  1]
 [-1  0  2 -1]]


In [49]:
M = np.dot(At, A)
print(M)

[[11  6 -4]
 [ 6  7  0]
 [-4  0  6]]


In [50]:
bt = np.dot(At,b)
bt

array([-3,  8, 10])

In [51]:
bsol = np.linalg.solve(M,bt)
bsol

array([-1.,  2.,  1.])

In [53]:
Proyección = A*bsol
Proyección

array([[-3.,  2., -1.],
       [-1.,  4.,  0.],
       [-0.,  2.,  2.],
       [-1.,  2., -1.]])

In [70]:
v0 = At[0]
v1 = At[1]
v2 = At[2]
u = np.zeros_like(At)
u[0] = At[0]  # El primer vector permanece igual
for i in range(1, At.shape[0]):
    u[i] = At[i] - np.sum(np.dot(At[i], u[j]) / np.dot(u[j], u[j]) * u[j] for j in range(i))

OB = u.T
Vect = OB.T
OB, Vect

/var/folders/2q/srj5vx4s1qd28nb9mz7c36x40000gn/T/ipykernel_1372/940900206.py:7: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  u[i] = At[i] - np.sum(np.dot(At[i], u[j]) / np.dot(u[j], u[j]) * u[j] for j in range(i))


(array([[3, 0, 0],
        [1, 1, 0],
        [0, 1, 1],
        [1, 0, 0]]),
 array([[3, 1, 0, 1],
        [0, 1, 1, 0],
        [0, 0, 1, 0]]))

In [68]:
c = np.zeros(len(Vect))
for i in range(len(Vect)):
    c[i] = np.dot(b, Vect[i])
    
c

ValueError: shapes (4,) and (3,) not aligned: 4 (dim 0) != 3 (dim 0)