In [83]:
import numpy as np
import matplotlib.pyplot as plt

In [84]:
b = np.array([-3, -3, 8, 9])
A = np.array([[3, 1, -1], [1, 2, 0], [0, 1, 2], [1, 1, -1]])

In [85]:
At = A.T

In [86]:
M = np.dot(At, A)

In [87]:
bt = np.dot(At,b)

In [88]:
bsol = np.linalg.solve(M,bt)

In [89]:
Proyección = A*bsol
Proyección

array([[-3.,  2., -1.],
       [-1.,  4.,  0.],
       [-0.,  2.,  2.],
       [-1.,  2., -1.]])

In [90]:
ProyT = Proyección.T
ProyT

array([[-3., -1., -0., -1.],
       [ 2.,  4.,  2.,  2.],
       [-1.,  0.,  2., -1.]])

In [91]:
u = np.zeros_like(ProyT)

In [92]:
for i in range(0, ProyT.shape[0]):
    u[i] = ProyT[i] - sum((np.dot(ProyT[i], u[j]) / np.dot(u[j], u[j])) * u[j] for j in range(i))
    u[i] = u[i] / np.linalg.norm(u[i])
u

array([[-0.90453403, -0.30151134, -0.        , -0.30151134],
       [-0.32961713,  0.75341057,  0.51796977,  0.2354408 ],
       [ 0.25633581, -0.26982716,  0.78249877, -0.49918025]])

In [93]:
c = np.zeros(len(u))
for i in range(len(u)):
    c[i] = np.dot(b, u[i])
P = 0
for i in range(len(c)):
    P += c[i]*u[i]
for i in range(len(P)):
    P[i] = round(P[i], 2)
P

array([-2.,  3.,  4., -0.])